#ssh对应的配置文件
[vm]
    #注解字段 用于 控制台显示
    Annota = "虚拟机"
    HostName = "192.168.5.234"
    Port = 22
    UserName ="root"
    Password = "2098231.xzm"

[stable]
    Annota = "稳定服"
    HostName = "27.159.65.91"
    Port = 22
    UserName ="root"
    Password = "zNb2iN1rmbT8"
