#ssh对应的配置文件
    HostName = "192.168.5.234"
    Port = 22
    UserName ="root"
    Password = "2098231.xzm"
#
#    HostName = "27.159.65.91"
#    Port = 22
#    UserName ="root"
#    Password = "2098231.xzm"
